keys:
  - &playserver age1yya0n3zg2z3n0zvf2k6kq07xeze2n6a7gn4u4ltfm74vhlg0kevsj3mg6g

creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *playserver